name: breach
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  another_flushbar: ^1.12.30
  flutter_animate: ^4.5.2
  auto_size_text: ^3.0.0
  flutter_dotenv: ^5.1.0
  formz: ^0.8.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  local_auth: ^2.3.0
  package_info_plus: ^8.3.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.17
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  equatable: ^2.0.5
  device_preview: ^1.2.0
  pretty_dio_logger: ^1.4.0
  animated_theme_switcher: ^2.0.10
  internet_connection_checker_plus: ^2.7.2
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  device_info_plus: ^11.4.0
  dart_ipify: ^1.1.1
  gif: ^2.3.0
  injectable_generator: ^2.7.0
  shimmer_animation: ^2.2.2
  web_socket_channel: ^3.0.3
  fast_cached_network_image: ^1.3.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/inter/Inter-Light.ttf
          weight: 300

    - family: SpaceGrotesk
      fonts:
        - asset: fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300